# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider:       fos_userbundle
            logout:       true
            anonymous:    true
            # activate different ways to authenticate

            #http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

    access_control:
        - { path: ^/add,  roles: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/\d+/edit, roles: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/\d+/remove, roles: IS_AUTHENTICATED_REMEMBERED }